name: Unit Tests

on:
   push:
      branches: [ master ]
      
jobs:
   build:
      name: Unit Tests
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            fetch-depth: 0
            
      -  name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
            distribution: temurin
            java-version: 11
            cache: gradle
            
      -  name: Make gradlew executable
         run: chmod +x ./gradlew
         
      -  name: Build and Test
         run: ./gradlew generateTestSource test jacocoTestReport --info -Dfull_test_suite=true --no-daemon
         
      -  name: show java process
         run: |
           sleep 60
           ps aux|grep java
